# Generated by Django 3.2.3 on 2021-06-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexisDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('A1', 'Beginner'), ('A2', 'PreIntermediate'), ('B1', 'Intermediate'), ('B2', 'UpperIntermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], default=0, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(blank=True, max_length=100)),
                ('translation', models.CharField(blank=True, max_length=100)),
                ('article', models.CharField(blank=True, max_length=100)),
                ('plural', models.CharField(blank=True, max_length=100)),
                ('context', models.CharField(blank=True, max_length=100)),
                ('meaning', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
