# Generated by Django 3.2.3 on 2021-06-05 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lexisDB', '0002_theme_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='theme',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lexisDB.theme'),
            preserve_default=False,
        ),
    ]
