# Generated by Django 3.2.3 on 2021-06-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexisDB', '0005_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='queue_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
