# Generated by Django 3.2.3 on 2021-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexisDB', '0006_auto_20210609_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio'),
        ),
    ]
