# Generated by Django 3.2.3 on 2021-06-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexisDB', '0007_word_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='queue_next_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
